[package]
name = "endian-type"
version = "0.1.0"
authors = ["Lolirofle <lolipopple@hotmail.com>"]
description = "Wrappers for types with a defined byte order"
#documentation = "..."
homepage = "https://github.com/Lolirofle/endian-type"
repository = "https://github.com/Lolirofle/endian-type.git"
#readme = "README.md"
keywords = ["endian","byteorder"]
license = "MIT"

[dependencies]
num = "*"
