[package]
name = "endian-type"
version = "0.1.3"
authors = ["Lolirofle <lolipopple@hotmail.com>","Jeffrey Burdges <burdges@gnunet.org>"]

description = "Type safe wrappers for byte order with conversion from/to byte arrays."
#documentation = "..."

homepage = "https://github.com/Lolirofle/endian-type"
repository = "https://github.com/Lolirofle/endian-type.git"

#readme = "README.md"

keywords = ["endian","byteorder"]

license = "MIT"

[dependencies]


